name: Release

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: '编译SDK版本'
        required: true
        default: '23.05.6'
        type: choice
        options:
        - 21.02.7
        - 22.03.7
        - 23.05.6
        - 24.10.5
        - 25.12.0-rc5
      build_flags:
        description: '编译选项'
        required: false
        type: string
        default: 'V=s'
      upload_artifact:
        description: '是否上传到Artifact'
        required: false
        type: boolean
        default: false
      upload_release:
        description: '是否上传到Release'
        required: false
        type: boolean
        default: true

jobs:
  build:
    name: Build with ${{ inputs.sdk_version }} ${{ inputs.build_flags }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Environment info
        run: |
          echo -e "Total CPU cores\t: $(nproc)"
          grep -m1 model /proc/cpuinfo
          free -h
          uname -a
          [ -f /proc/version ] && cat /proc/version
          [ -f /etc/issue.net ] && cat /etc/issue.net
          ulimit -a

      - name: Download OpenWRT SDK v${{ inputs.sdk_version }}
        run: |
          wget -rLl1 -nd -P ${{ runner.tool_cache }}/openwrt-sdk --reject-regex /$ --progress=dot:giga \
            https://archive.openwrt.org/releases/${{ inputs.sdk_version }}/targets/x86/64/ -A openwrt-sdk-*.tar.*
          cd ${{ runner.tool_cache }}/openwrt-sdk
          tar --strip-components=1 -xf openwrt-sdk-*.tar.*
          rm openwrt-sdk-*.tar.*

      - name: Install feeds
        working-directory: '${{ runner.tool_cache }}/openwrt-sdk'
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        working-directory: '${{ runner.tool_cache }}/openwrt-sdk'
        run: |
          ln -sf $GITHUB_WORKSPACE package/luci-theme-design
          echo "CONFIG_PACKAGE_luci-theme-design=y" >> .config
          make defconfig

      - name: Build
        id: build
        working-directory: '${{ runner.tool_cache }}/openwrt-sdk'
        run: |
          make package/luci-theme-design/compile -j$(nproc) ${{ inputs.build_flags }}
          TARGET=$(echo bin/packages/x86_64/base/luci-theme-design-*.*)
          echo "TARGET=$(pwd)/$TARGET" | tee -a $GITHUB_OUTPUT

      - name: Upload to artifact
        uses: actions/upload-artifact@master
        if: github.event.inputs.upload_artifact
        with:
          name: luci-theme-design-${{ inputs.sdk_version }}
          path: ${{ steps.build.outputs.TARGET }}

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        if: github.event.inputs.upload_release
        with:
          generate_release_notes: true
          files: |
            ${{ steps.build.outputs.TARGET }}
            LICENSE
